### ISSUE TITLE
Face normals weird when tryo

### ISSUE THREAD

**Issue by luiscruzreyes001** [croakfang/UmaMusumeMME#1]
Hi i wanted to try the sahder but i found an issue i think its not recognizing this line? 
float4x4 _faceShadowHeadMat : CONTROLOBJECT < string name = "(self)"; string item = "摢"; >
because this is not working (float _faceShadowAlpha = 0;) properly and shadow looks broken when i move face bone 
<img width="620" alt="image" src="https://github.com/croakfang/UmaMusumeMME/assets/60833424/ba3ed231-7a60-4e31-9524-5f3696367b50">
thank you in advance

**Comment by croakfang** [comment]
It may be caused by encoding, try add a bone `head` to the model, set its parent bone as the `頭`, then replace "摢" to "head" :
`float4x4 _faceShadowHeadMat : CONTROLOBJECT < string name = "(self)"; string item = "head"; >`

**Comment by luiscruzreyes001** [comment]
@croakfang thank you so much it worked fine but now there is another problem with shadow alpha when i try to add the blue shadow on face now this one moves weird not how it suppose to 

https://github.com/croakfang/UmaMusumeMME/assets/60833424/0cd01d01-493c-449f-9deb-a8c52810194f

i think it suppose to get stuck in the eyes but it moves as a shadow. sorry if i am pointing out errors its just i like the shader so much. and thanks in advance

**Comment by croakfang** [comment]
blue shadow is not supported because MMD is missing some information. It is best not to use it

**Comment by luiscruzreyes001** [comment]
@croakfang hi again i am a noob on shaders but i tried to add RFL function to this amazing shader
[UMA_Body.zip](https://github.com/croakfang/UmaMusumeMME/files/13805994/UMA_Body.zip)
it uses the RFL map red and green channel +  the red channel of option mask 
the variables i added where _RFLRate and r10, r11
it just a test since i am not that good at editing .fx but ifyou think this option works or need more adjustements. i would be glad to know.

I am also thinking on a good implementation and those would be adding 3 different colors on dirtmap like RGB not only one global color and an effect postalpha eye 
<img width="564" alt="image" src="https://github.com/croakfang/UmaMusumeMME/assets/60833424/595d3993-3afb-4327-84e3-157b15f79369">
I am trying to edit those but i think you merged those 3 maps here
	r3.xyz = _DirtScale.xxx * r3.xyz;
	r3.y = _DirtRate[1].x * r3.y;
	r3.x = r3.x * _DirtRate[0] + r3.y;
	r3.x = r3.z * _DirtRate[2] + r3.x;
	r3.y = cmp(-0 >= _RimHorizonOffset);
it would be a good idea separating them? 
also if you want i think i can help a little by making a controller so some values can be edited in mmd with a controller.pmx what do you think?
have a good day
